/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package try4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class DeleteCourse extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCourse
     */
    public DeleteCourse() {
        initComponents();
        Panel_RemStream.setVisible(false);
        Panel_RemBranch.setVisible(false);
        Panel_RemSem.setVisible(false);
        Panel_RemSub.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_RemStream = new javax.swing.JButton();
        Button_RemBranch = new javax.swing.JButton();
        Button_RemSem = new javax.swing.JButton();
        Button_RemSub = new javax.swing.JButton();
        Panel_RemStream = new javax.swing.JPanel();
        ComboBox_StreamRemove = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Button_DeleteStream = new javax.swing.JButton();
        Button_CancelStream = new javax.swing.JButton();
        Panel_RemBranch = new javax.swing.JPanel();
        ComboBox_StreamBranch = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Button_DeleteBranch = new javax.swing.JButton();
        Button_CancelBranch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_BranchRemove = new javax.swing.JComboBox();
        Panel_RemSem = new javax.swing.JPanel();
        ComboBox_StreamSem = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Button_DeleteSem = new javax.swing.JButton();
        Button_CancelSem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboBox_BranchSem = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        ComboBox_SemRemove = new javax.swing.JComboBox();
        Panel_RemSub = new javax.swing.JPanel();
        ComboBox_StreamSub = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Button_DeleteSub = new javax.swing.JButton();
        Button_CancelSub = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ComboBox_BranchSub = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ComboBox_SemSub = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        ComboBox_SubRemove = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Delete Course");

        Button_RemStream.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_RemStream.setText("Remove Stream");
        Button_RemStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemStreamActionPerformed(evt);
            }
        });

        Button_RemBranch.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_RemBranch.setText("Remove Branch");
        Button_RemBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemBranchActionPerformed(evt);
            }
        });

        Button_RemSem.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_RemSem.setText("Remove Semester");
        Button_RemSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemSemActionPerformed(evt);
            }
        });

        Button_RemSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_RemSub.setText("Remove Subject");
        Button_RemSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemSubActionPerformed(evt);
            }
        });

        Panel_RemStream.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ComboBox_StreamRemove.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_StreamRemove.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_StreamRemovePopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("Select the Stream to Remove:");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel2.setText("Remove Stream");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Button_DeleteStream.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_DeleteStream.setText("Delete");
        Button_DeleteStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteStreamActionPerformed(evt);
            }
        });

        Button_CancelStream.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_CancelStream.setText("Cancel");
        Button_CancelStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelStreamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_RemStreamLayout = new javax.swing.GroupLayout(Panel_RemStream);
        Panel_RemStream.setLayout(Panel_RemStreamLayout);
        Panel_RemStreamLayout.setHorizontalGroup(
            Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemStreamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_RemStreamLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(ComboBox_StreamRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RemStreamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_DeleteStream, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_CancelStream, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        Panel_RemStreamLayout.setVerticalGroup(
            Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemStreamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox_StreamRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_RemStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CancelStream)
                    .addComponent(Button_DeleteStream))
                .addGap(171, 171, 171))
        );

        Panel_RemBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ComboBox_StreamBranch.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_StreamBranch.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_StreamBranchPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setText("Select the Stream:");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel4.setText("Remove Branch");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        Button_DeleteBranch.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_DeleteBranch.setText("Delete");
        Button_DeleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteBranchActionPerformed(evt);
            }
        });

        Button_CancelBranch.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_CancelBranch.setText("Cancel");
        Button_CancelBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelBranchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel5.setText("Select the Branch to Remove:");

        ComboBox_BranchRemove.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_BranchRemove.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_BranchRemovePopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout Panel_RemBranchLayout = new javax.swing.GroupLayout(Panel_RemBranch);
        Panel_RemBranch.setLayout(Panel_RemBranchLayout);
        Panel_RemBranchLayout.setHorizontalGroup(
            Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemBranchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_StreamBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_BranchRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RemBranchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_DeleteBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_CancelBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        Panel_RemBranchLayout.setVerticalGroup(
            Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemBranchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBox_StreamBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_BranchRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(Panel_RemBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CancelBranch)
                    .addComponent(Button_DeleteBranch))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        Panel_RemSem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ComboBox_StreamSem.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_StreamSem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_StreamSemPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setText("Select the Stream:");

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel7.setText("Remove Semester");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        Button_DeleteSem.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_DeleteSem.setText("Delete");
        Button_DeleteSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteSemActionPerformed(evt);
            }
        });

        Button_CancelSem.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_CancelSem.setText("Cancel");
        Button_CancelSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelSemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setText("Select the Branch:");

        ComboBox_BranchSem.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_BranchSem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_BranchSemPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel9.setText("Select the  Semester to Remove:");

        ComboBox_SemRemove.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_SemRemove.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_SemRemovePopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout Panel_RemSemLayout = new javax.swing.GroupLayout(Panel_RemSem);
        Panel_RemSem.setLayout(Panel_RemSemLayout);
        Panel_RemSemLayout.setHorizontalGroup(
            Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemSemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(Panel_RemSemLayout.createSequentialGroup()
                        .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(131, 131, 131)
                        .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_BranchSem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_StreamSem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_SemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RemSemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_DeleteSem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_CancelSem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        Panel_RemSemLayout.setVerticalGroup(
            Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemSemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboBox_StreamSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboBox_BranchSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ComboBox_SemRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(Panel_RemSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CancelSem)
                    .addComponent(Button_DeleteSem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_RemSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ComboBox_StreamSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_StreamSub.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_StreamSubPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel10.setText("Select the Stream:");

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel11.setText("Remove Subject");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        Button_DeleteSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_DeleteSub.setText("Delete");
        Button_DeleteSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteSubActionPerformed(evt);
            }
        });

        Button_CancelSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_CancelSub.setText("Cancel");
        Button_CancelSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelSubActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel12.setText("Select the Branch:");

        ComboBox_BranchSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_BranchSub.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_BranchSubPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel13.setText("Select the Semester:");

        ComboBox_SemSub.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_SemSub.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_SemSubPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel14.setText("Select the Subject to Remove:");

        ComboBox_SubRemove.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ComboBox_SubRemove.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_SubRemovePopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout Panel_RemSubLayout = new javax.swing.GroupLayout(Panel_RemSub);
        Panel_RemSub.setLayout(Panel_RemSubLayout);
        Panel_RemSubLayout.setHorizontalGroup(
            Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemSubLayout.createSequentialGroup()
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RemSubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(Panel_RemSubLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Button_DeleteSub, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_CancelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_RemSubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(131, 131, 131)
                        .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_SubRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_BranchSub, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_StreamSub, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_SemSub, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Panel_RemSubLayout.setVerticalGroup(
            Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RemSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ComboBox_StreamSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ComboBox_BranchSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ComboBox_SemSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ComboBox_SubRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(Panel_RemSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_DeleteSub)
                    .addComponent(Button_CancelSub))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_RemStream, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_RemBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_RemSem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_RemSub, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1578, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_RemStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_RemBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_RemSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_RemSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_RemSub)
                    .addComponent(Button_RemSem)
                    .addComponent(Button_RemBranch)
                    .addComponent(Button_RemStream))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_RemSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_RemSem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_RemBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_RemStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        Panel_RemStream.setVisible(false);
        Panel_RemBranch.setVisible(false);
        Panel_RemSem.setVisible(false);
        Panel_RemSub.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RemStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemStreamActionPerformed
        // TODO add your handling code here:
        Panel_RemStream.setVisible(true);
        Panel_RemBranch.setVisible(false);
        Panel_RemSem.setVisible(false);
        Panel_RemSub.setVisible(false);
    }//GEN-LAST:event_Button_RemStreamActionPerformed

    private void Button_RemBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemBranchActionPerformed
        // TODO add your handling code here:
        Panel_RemStream.setVisible(false);
        Panel_RemBranch.setVisible(true);
        Panel_RemSem.setVisible(false);
        Panel_RemSub.setVisible(false);
    }//GEN-LAST:event_Button_RemBranchActionPerformed

    private void Button_RemSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemSubActionPerformed
        // TODO add your handling code here:
        Panel_RemStream.setVisible(false);
        Panel_RemBranch.setVisible(false);
        Panel_RemSem.setVisible(false);
        Panel_RemSub.setVisible(true);
    }//GEN-LAST:event_Button_RemSubActionPerformed
    
    private void Button_DeleteStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteStreamActionPerformed
        // TODO add your handling code here:
        String stream = ComboBox_StreamRemove.getSelectedItem().toString();    
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
                String sql = "delete from course where stream=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, stream);
                ResultSet rs = ps.executeQuery();    
                int ret = JOptionPane.showConfirmDialog(this, "Are you sure you want to Remove this Stream?\nAll the Branches and Semesters of this Stream will also be Removed");
                if(ret==0)
                {
                    while(rs.next())
                    {
                        JOptionPane.showMessageDialog(this,"Stream Removed");
                    }
                }
                else if(ret==1 || ret==2)
                {
                    JOptionPane.showMessageDialog(this,"Stream Not Removed");
                }
            }
            catch(ClassNotFoundException e)
            {}
            catch(Exception e)
            {}
    }//GEN-LAST:event_Button_DeleteStreamActionPerformed

    private void Button_CancelStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelStreamActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_CancelStreamActionPerformed

    private void ComboBox_StreamRemovePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_StreamRemovePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ComboBox_StreamRemove.removeAllItems();
        ComboBox_StreamRemove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct stream from course ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_StreamRemove.addItem(rs.getString("stream"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}

    }//GEN-LAST:event_ComboBox_StreamRemovePopupMenuWillBecomeVisible

    private void ComboBox_StreamBranchPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_StreamBranchPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ComboBox_StreamBranch.removeAllItems();
        ComboBox_StreamBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct stream from course ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_StreamBranch.addItem(rs.getString("stream"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}

    }//GEN-LAST:event_ComboBox_StreamBranchPopupMenuWillBecomeVisible

    private void Button_DeleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteBranchActionPerformed
        // TODO add your handling code here:
        String stream = ComboBox_StreamRemove.getSelectedItem().toString();    
        String branch = ComboBox_BranchRemove.getSelectedItem().toString();
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
                String sql = "delete from course where stream=? and branch=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, stream);
                ps.setString(2, branch);
                ResultSet rs = ps.executeQuery();    
                int ret = JOptionPane.showConfirmDialog(this, "Are you sure you want to Remove this Branch?\nAll the Semesters of this Branch will also be Removed");
                if(ret==0)
                {
                    while(rs.next())
                    {
                        JOptionPane.showMessageDialog(this,"Branch Removed");
                    }
                }
                else if(ret==1 || ret==2)
                {
                    JOptionPane.showMessageDialog(this,"Branch Not Removed");
                }
            }
            catch(ClassNotFoundException e)
            {}
            catch(Exception e)
            {}
    }//GEN-LAST:event_Button_DeleteBranchActionPerformed

    private void Button_CancelBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelBranchActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_CancelBranchActionPerformed

    private void ComboBox_BranchRemovePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_BranchRemovePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamBranch.getSelectedItem().toString();
        ComboBox_BranchRemove.removeAllItems();
        ComboBox_BranchRemove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_BranchRemove.addItem(rs.getString("branch"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_BranchRemovePopupMenuWillBecomeVisible

    private void ComboBox_StreamSemPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_StreamSemPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ComboBox_StreamSem.removeAllItems();
        ComboBox_StreamSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct stream from course ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_StreamSem.addItem(rs.getString("stream"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}

    }//GEN-LAST:event_ComboBox_StreamSemPopupMenuWillBecomeVisible

    private void Button_DeleteSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteSemActionPerformed
        // TODO add your handling code here:
        String stream = ComboBox_StreamSem.getSelectedItem().toString();
        String branch = ComboBox_BranchSem.getSelectedItem().toString();
        String sem = ComboBox_SemRemove.getSelectedItem().toString();
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
                String sql = "delete from course where stream=? and branch=? and sem=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, stream);
                ps.setString(2, branch);
                ps.setString(3, sem);
                ResultSet rs = ps.executeQuery();    
                int ret = JOptionPane.showConfirmDialog(this, "Are you sure you want to Remove this Semester?");
                if(ret==0)
                {
                    while(rs.next())
                    {
                        JOptionPane.showMessageDialog(this,"Semester Removed");
                    }
                }
                else if(ret==1 || ret==2)
                {
                    JOptionPane.showMessageDialog(this,"Semester Not Removed");
                }
            }
            catch(ClassNotFoundException e)
            {}
            catch(Exception e)
            {}
    }//GEN-LAST:event_Button_DeleteSemActionPerformed

    private void Button_CancelSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelSemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_CancelSemActionPerformed

    private void ComboBox_BranchSemPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_BranchSemPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamSem.getSelectedItem().toString();
        ComboBox_BranchSem.removeAllItems();
        ComboBox_BranchSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_BranchSem.addItem(rs.getString("branch"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_BranchSemPopupMenuWillBecomeVisible

    private void ComboBox_SemRemovePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_SemRemovePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamBranch.getSelectedItem().toString();
        String branch = ComboBox_BranchSem.getSelectedItem().toString();
        ComboBox_SemRemove.removeAllItems();
        ComboBox_SemRemove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=? and branch=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_SemRemove.addItem(rs.getString("sem"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_SemRemovePopupMenuWillBecomeVisible

    private void ComboBox_StreamSubPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_StreamSubPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        ComboBox_StreamSub.removeAllItems();
        ComboBox_StreamSub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct stream from course ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_StreamSub.addItem(rs.getString("stream"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_StreamSubPopupMenuWillBecomeVisible

    private void Button_DeleteSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteSubActionPerformed
        // TODO add your handling code here:
        String stream = ComboBox_StreamSem.getSelectedItem().toString();
        String branch = ComboBox_BranchSem.getSelectedItem().toString();
        String sem = ComboBox_SemRemove.getSelectedItem().toString();
        String sub = ComboBox_SubRemove.getSelectedItem().toString();
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
                String sql = "delete from course where stream=? and branch=? and sem=? and subject=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, stream);
                ps.setString(2, branch);
                ps.setString(3, sem);
                ps.setString(4, sub);
                ResultSet rs = ps.executeQuery();    
                int ret = JOptionPane.showConfirmDialog(this, "Are you sure you want to Remove this Subject?");
                if(ret==0)
                {
                    while(rs.next())
                    {
                        JOptionPane.showMessageDialog(this,"Subject Removed");
                    }
                }
                else if(ret==1 || ret==2)
                {
                    JOptionPane.showMessageDialog(this,"Subject Not Removed");
                }
            }
            catch(ClassNotFoundException e)
            {}
            catch(Exception e)
            {}
    }//GEN-LAST:event_Button_DeleteSubActionPerformed

    private void Button_CancelSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelSubActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_CancelSubActionPerformed

    private void ComboBox_BranchSubPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_BranchSubPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamSub.getSelectedItem().toString();
        ComboBox_BranchSub.removeAllItems();
        ComboBox_BranchSub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_BranchSub.addItem(rs.getString("branch"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_BranchSubPopupMenuWillBecomeVisible

    private void ComboBox_SemSubPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_SemSubPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamSub.getSelectedItem().toString();
        String branch = ComboBox_BranchSub.getSelectedItem().toString();
        ComboBox_SubRemove.removeAllItems();
        ComboBox_SubRemove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=? and branch=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_SubRemove.addItem(rs.getString("sem"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_SemSubPopupMenuWillBecomeVisible

    private void ComboBox_SubRemovePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_SubRemovePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        String stream = ComboBox_StreamSub.getSelectedItem().toString();
        String branch = ComboBox_BranchSub.getSelectedItem().toString();
        String sem = ComboBox_SemSub.getSelectedItem().toString();
        ComboBox_SubRemove.removeAllItems();
        ComboBox_SubRemove.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select Stream ---"}));
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql = "select distinct branch from course where stream=? and branch=? and sem=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ps.setString(3, sem);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {   
                ComboBox_SubRemove.addItem(rs.getString("sem"));
            }
        }   
        catch(ClassNotFoundException e)
        { System.out.println(e);}
        catch(Exception e)
        { System.out.println(e);}
    }//GEN-LAST:event_ComboBox_SubRemovePopupMenuWillBecomeVisible

    private void Button_RemSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemSemActionPerformed
        // TODO add your handling code here:
        Panel_RemStream.setVisible(false);
        Panel_RemBranch.setVisible(false);
        Panel_RemSem.setVisible(true);
        Panel_RemSub.setVisible(false);
    }//GEN-LAST:event_Button_RemSemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeleteCourse().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_CancelBranch;
    public javax.swing.JButton Button_CancelSem;
    public javax.swing.JButton Button_CancelStream;
    public javax.swing.JButton Button_CancelSub;
    public javax.swing.JButton Button_DeleteBranch;
    public javax.swing.JButton Button_DeleteSem;
    public javax.swing.JButton Button_DeleteStream;
    public javax.swing.JButton Button_DeleteSub;
    private javax.swing.JButton Button_RemBranch;
    private javax.swing.JButton Button_RemSem;
    private javax.swing.JButton Button_RemStream;
    private javax.swing.JButton Button_RemSub;
    public javax.swing.JComboBox ComboBox_BranchRemove;
    public javax.swing.JComboBox ComboBox_BranchSem;
    public javax.swing.JComboBox ComboBox_BranchSub;
    public javax.swing.JComboBox ComboBox_SemRemove;
    public javax.swing.JComboBox ComboBox_SemSub;
    public javax.swing.JComboBox ComboBox_StreamBranch;
    public javax.swing.JComboBox ComboBox_StreamRemove;
    public javax.swing.JComboBox ComboBox_StreamSem;
    public javax.swing.JComboBox ComboBox_StreamSub;
    public javax.swing.JComboBox ComboBox_SubRemove;
    private javax.swing.JPanel Panel_RemBranch;
    private javax.swing.JPanel Panel_RemSem;
    private javax.swing.JPanel Panel_RemStream;
    private javax.swing.JPanel Panel_RemSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
