/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package try4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class StudentAdmissionWindow extends javax.swing.JFrame {

    /**
     * Creates new form StudentAdmissionWindow
     */
    public StudentAdmissionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Label_Test3 = new javax.swing.JLabel();
        Label_Test4 = new javax.swing.JLabel();
        Label_StdNameReport1 = new javax.swing.JLabel();
        TextField_Test3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextField_Test4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TextField_StdNameReport1 = new javax.swing.JTextField();
        Label_AttndnceReport12 = new javax.swing.JLabel();
        Label_AttndnceReport13 = new javax.swing.JLabel();
        TextField_Attndnce12 = new javax.swing.JTextField();
        TextField_Attndnce13 = new javax.swing.JTextField();
        TextField_Attndnce14 = new javax.swing.JTextField();
        Label_AttndnceReport14 = new javax.swing.JLabel();
        Label_AttndnceReport15 = new javax.swing.JLabel();
        TextField_Attndnce15 = new javax.swing.JTextField();
        Label_AttndnceReport16 = new javax.swing.JLabel();
        TextField_Attndnce16 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        TextField_StdCategAdm = new javax.swing.JTextField();
        TextField_StdBloodAdm = new javax.swing.JTextField();
        Label_AttndnceReport = new javax.swing.JLabel();
        TextField_StdNameAdm = new javax.swing.JTextField();
        Label_StdIDReport = new javax.swing.JLabel();
        Label_StdNameReport = new javax.swing.JLabel();
        TextField_StdRegNumAdm = new javax.swing.JTextField();
        Label_Test2 = new javax.swing.JLabel();
        Label_Test1 = new javax.swing.JLabel();
        TextField_StdDOBAdm = new javax.swing.JTextField();
        Label_Assgmnt2 = new javax.swing.JLabel();
        TextField_StdStreamAdm = new javax.swing.JTextField();
        Label_Assgmnt1 = new javax.swing.JLabel();
        TextField_StdGenAdm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_AttndnceReport1 = new javax.swing.JLabel();
        Label_AttndnceReport2 = new javax.swing.JLabel();
        Label_AttndnceReport3 = new javax.swing.JLabel();
        Label_AttndnceReport4 = new javax.swing.JLabel();
        Label_AttndnceReport5 = new javax.swing.JLabel();
        Label_AttndnceReport6 = new javax.swing.JLabel();
        Label_AttndnceReport7 = new javax.swing.JLabel();
        Label_AttndnceReport8 = new javax.swing.JLabel();
        Label_AttndnceReport9 = new javax.swing.JLabel();
        Label_AttndnceReport10 = new javax.swing.JLabel();
        Label_AttndnceReport11 = new javax.swing.JLabel();
        Button_AccptStdAdm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TextField_StdBranchAdm = new javax.swing.JTextField();
        TextField_Std10Adm = new javax.swing.JTextField();
        TextField_Std12Adm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextField_StdScoreAdm = new javax.swing.JTextField();
        TextField_StdYearAdm = new javax.swing.JTextField();
        TextField_StdFatherAdm = new javax.swing.JTextField();
        TextField_StdMotherAdm = new javax.swing.JTextField();
        TextField_StdAddAdm = new javax.swing.JTextField();
        TextField_StdPhoneAdm = new javax.swing.JTextField();
        TextField_StdParentPhoneAdm = new javax.swing.JTextField();
        TextField_StdEmailAdm = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollBar2 = new javax.swing.JScrollBar();
        Label_AttndnceReport17 = new javax.swing.JLabel();
        TextField_StdSemAdm = new javax.swing.JTextField();
        Label_AttndnceReport18 = new javax.swing.JLabel();
        TextField_RegDate = new javax.swing.JTextField();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Admission Accepted");

        Label_Test3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test3.setText("Gender:");
        Label_Test3.setToolTipText("Admission Accepted");

        Label_Test4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test4.setText("Registration Number:");
        Label_Test4.setToolTipText("Admission Accepted");

        Label_StdNameReport1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_StdNameReport1.setText("Name:");
        Label_StdNameReport1.setToolTipText("Admission Accepted");

        TextField_Test3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Test3.setToolTipText("Admission Accepted");
        TextField_Test3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel4.setText("Admission Successful");
        jLabel4.setToolTipText("Admission Accepted");

        TextField_Test4.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Test4.setToolTipText("Admission Accepted");
        TextField_Test4.setEnabled(false);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("Admission Accepted");

        TextField_StdNameReport1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdNameReport1.setToolTipText("Admission Accepted");
        TextField_StdNameReport1.setEnabled(false);

        Label_AttndnceReport12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport12.setText("Branch:");

        Label_AttndnceReport13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport13.setText("Year:");

        TextField_Attndnce12.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Attndnce12.setEnabled(false);

        TextField_Attndnce13.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Attndnce13.setEnabled(false);

        TextField_Attndnce14.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Attndnce14.setEnabled(false);

        Label_AttndnceReport14.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport14.setText("Stream:");

        Label_AttndnceReport15.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport15.setText("Roll Number:");

        TextField_Attndnce15.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Attndnce15.setEnabled(false);

        Label_AttndnceReport16.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport16.setText("Student ID:");

        TextField_Attndnce16.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Attndnce16.setEnabled(false);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setToolTipText("Admission Accepted");

        jButton3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jButton3.setText("Done");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_StdNameReport1)
                            .addComponent(Label_Test4)
                            .addComponent(Label_Test3)
                            .addComponent(Label_AttndnceReport15)
                            .addComponent(Label_AttndnceReport16)
                            .addComponent(Label_AttndnceReport13))
                        .addGap(27, 27, 27)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Attndnce13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Attndnce16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Attndnce15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Attndnce14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Test4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Test3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_StdNameReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Attndnce12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Label_AttndnceReport14)
                                    .addComponent(Label_AttndnceReport12))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator4))
                        .addContainerGap())))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_StdNameReport1)
                    .addComponent(TextField_StdNameReport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Test4)
                    .addComponent(TextField_Test3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Test3)
                    .addComponent(TextField_Test4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport14)
                    .addComponent(TextField_Attndnce12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport12)
                    .addComponent(TextField_Attndnce14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport15)
                    .addComponent(TextField_Attndnce15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport16)
                    .addComponent(TextField_Attndnce16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport13)
                    .addComponent(TextField_Attndnce13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Student Admission");

        TextField_StdCategAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdCategAdm.setEnabled(false);

        TextField_StdBloodAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdBloodAdm.setEnabled(false);

        Label_AttndnceReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport.setText("Stream:");

        TextField_StdNameAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdNameAdm.setEnabled(false);

        Label_StdIDReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_StdIDReport.setText("D.O.B.:");

        Label_StdNameReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_StdNameReport.setText("Name:");

        TextField_StdRegNumAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdRegNumAdm.setEnabled(false);

        Label_Test2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test2.setText("Gender:");

        Label_Test1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test1.setText("Registration Number:");

        TextField_StdDOBAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdDOBAdm.setEnabled(false);
        TextField_StdDOBAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StdDOBAdmActionPerformed(evt);
            }
        });

        Label_Assgmnt2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Assgmnt2.setText("Blood Group:");

        TextField_StdStreamAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdStreamAdm.setEnabled(false);

        Label_Assgmnt1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Assgmnt1.setText("Category:");

        TextField_StdGenAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdGenAdm.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel1.setText("Student Details");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Label_AttndnceReport1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport1.setText("Branch:");

        Label_AttndnceReport2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport2.setText("10th %");

        Label_AttndnceReport3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport3.setText("12th %:");

        Label_AttndnceReport4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport4.setText("Entrance Test Score:");

        Label_AttndnceReport5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport5.setText("Year:");

        Label_AttndnceReport6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport6.setText("Father's Name:");

        Label_AttndnceReport7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport7.setText("Mother's Name:");

        Label_AttndnceReport8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport8.setText("Address:");

        Label_AttndnceReport9.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport9.setText("Contact Number:");

        Label_AttndnceReport10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport10.setText("Parent's Contact Number:");

        Label_AttndnceReport11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport11.setText("E-mail Address:");

        Button_AccptStdAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_AccptStdAdm.setText("Accept");
        Button_AccptStdAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AccptStdAdmActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jButton2.setText("Decline");

        TextField_StdBranchAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdBranchAdm.setEnabled(false);

        TextField_Std10Adm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Std10Adm.setEnabled(false);

        TextField_Std12Adm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_Std12Adm.setEnabled(false);

        jLabel2.setText("%");

        jLabel3.setText("%");

        TextField_StdScoreAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdScoreAdm.setEnabled(false);

        TextField_StdYearAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdYearAdm.setEnabled(false);

        TextField_StdFatherAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdFatherAdm.setEnabled(false);

        TextField_StdMotherAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdMotherAdm.setEnabled(false);

        TextField_StdAddAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdAddAdm.setEnabled(false);
        TextField_StdAddAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StdAddAdmActionPerformed(evt);
            }
        });

        TextField_StdPhoneAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdPhoneAdm.setEnabled(false);
        TextField_StdPhoneAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StdPhoneAdmActionPerformed(evt);
            }
        });

        TextField_StdParentPhoneAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdParentPhoneAdm.setEnabled(false);
        TextField_StdParentPhoneAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StdParentPhoneAdmActionPerformed(evt);
            }
        });

        TextField_StdEmailAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdEmailAdm.setEnabled(false);
        TextField_StdEmailAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StdEmailAdmActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jScrollBar2.setAutoscrolls(true);
        jScrollBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Label_AttndnceReport17.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport17.setText("Semester:");

        TextField_StdSemAdm.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StdSemAdm.setEnabled(false);

        Label_AttndnceReport18.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport18.setText("Registration Date:");

        TextField_RegDate.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_RegDate.setEnabled(false);
        TextField_RegDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_RegDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_StdNameReport)
                                            .addComponent(Label_StdIDReport)
                                            .addComponent(Label_Test1)
                                            .addComponent(Label_Test2)
                                            .addComponent(Label_Assgmnt1)
                                            .addComponent(Label_Assgmnt2)
                                            .addComponent(Label_AttndnceReport)
                                            .addComponent(Label_AttndnceReport1)
                                            .addComponent(Label_AttndnceReport2)
                                            .addComponent(Label_AttndnceReport3)
                                            .addComponent(Label_AttndnceReport4)
                                            .addComponent(Label_AttndnceReport5)
                                            .addComponent(Label_AttndnceReport6)
                                            .addComponent(Label_AttndnceReport7)
                                            .addComponent(Label_AttndnceReport8)
                                            .addComponent(Label_AttndnceReport9)
                                            .addComponent(Label_AttndnceReport10)
                                            .addComponent(Label_AttndnceReport11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextField_StdBranchAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdStreamAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdBloodAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdCategAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdGenAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdRegNumAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdDOBAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdNameAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdParentPhoneAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdPhoneAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdMotherAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdFatherAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdAddAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdEmailAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdYearAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_StdScoreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TextField_Std12Adm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TextField_Std10Adm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TextField_StdSemAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)))
                                            .addComponent(TextField_RegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)
                                        .addComponent(Button_AccptStdAdm))
                                    .addComponent(jLabel1))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_AttndnceReport17)
                                    .addComponent(Label_AttndnceReport18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(236, 236, 236))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_StdNameReport)
                                    .addComponent(TextField_StdNameAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_StdIDReport)
                                    .addComponent(TextField_StdDOBAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_Test1)
                                    .addComponent(TextField_StdRegNumAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_Test2)
                                    .addComponent(TextField_StdGenAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_Assgmnt1)
                                    .addComponent(TextField_StdCategAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_Assgmnt2)
                                    .addComponent(TextField_StdBloodAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport)
                                    .addComponent(TextField_StdStreamAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport1)
                                    .addComponent(TextField_StdBranchAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport17)
                                    .addComponent(TextField_StdSemAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextField_Std10Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(Label_AttndnceReport2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport3)
                                    .addComponent(TextField_Std12Adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport4)
                                    .addComponent(TextField_StdScoreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport5)
                                    .addComponent(TextField_StdYearAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport6)
                                    .addComponent(TextField_StdFatherAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport7)
                                    .addComponent(TextField_StdMotherAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport8)
                                    .addComponent(TextField_StdAddAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport9)
                                    .addComponent(TextField_StdPhoneAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport10)
                                    .addComponent(TextField_StdParentPhoneAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_AttndnceReport11)
                                    .addComponent(TextField_StdEmailAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(Button_AccptStdAdm)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_AttndnceReport18)
                            .addComponent(TextField_RegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_StdAddAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StdAddAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StdAddAdmActionPerformed

    private void TextField_StdPhoneAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StdPhoneAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StdPhoneAdmActionPerformed

    private void TextField_StdParentPhoneAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StdParentPhoneAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StdParentPhoneAdmActionPerformed

    private void TextField_StdEmailAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StdEmailAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StdEmailAdmActionPerformed
String sid1,sid2,roll3;
int sid3,sid4,streamid,branchid,roll1,roll2,roll4,roll5;
    private void Button_AccptStdAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AccptStdAdmActionPerformed
        // TODO add your handling code here:
        String stream = TextField_StdStreamAdm.getText();
        String branch = TextField_StdBranchAdm.getText();
        String year = TextField_StdYearAdm.getText();
        //String sem = TextField_StdSemAdm.getText();
        StudentAdmssnAccept sa = new StudentAdmssnAccept();
        sa.setVisible(true);
        this.setVisible(false);
        int GetID=0;
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@LocalHost:1521:XE","SYSTEM","sagar");
            String sql = "select count(*) from s_details where stream=? and branch=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                GetID=rs.getInt("s_id");
                roll1=rs.getInt("roll_no");
            }
        }
        catch(ClassNotFoundException e)
        {}
        catch(Exception e)
        {}
        java.util.Date today = Calendar.getInstance().getTime();
        SimpleDateFormat formatter = new SimpleDateFormat("yy");
        String s = formatter.format(today);
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
            String sql ="select * from course where stream=? and branch=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ResultSet rs = ps.executeQuery();
            while(rs.next());
            {
                streamid=rs.getInt("stream_id");
                branchid=rs.getInt("branch_id");
            }
        }
        catch(ClassNotFoundException e)
        {}
        catch(Exception e)
        {}
        roll4=Integer.parseInt(s);
        roll2=roll1+1;
        roll3=""+streamid+branchid+roll4+roll1;
        roll5=Integer.parseInt(roll3);
        sid3=GetID+1;
        sid2=stream+year+branch+sid3;
        sa.TextField_NameStdAccpt.setText(TextField_StdNameAdm.getText());
        sa.TextField_RegNoStdAccpt.setText(TextField_StdRegNumAdm.getText());
        sa.TextField_GendStdAccpt.setText(TextField_StdGenAdm.getText());
        sa.TextField_SteramStdAccpt.setText(TextField_StdStreamAdm.getText());
        sa.TextField_BranchStdAccpt.setText(TextField_StdBranchAdm.getText());
        sa.TextField_RollStdAccpt.setText(roll3);
        sa.TextField_StdIDStdAccpt.setText(sid2);
        sa.TextField_YearStdAccpt.setText(TextField_StdYearAdm.getText());
        sa.TextField_SemStdAccpt.setText(TextField_StdSemAdm.getText());
    }//GEN-LAST:event_Button_AccptStdAdmActionPerformed

    private void TextField_StdDOBAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StdDOBAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StdDOBAdmActionPerformed

    private void TextField_RegDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_RegDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RegDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAdmissionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAdmissionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAdmissionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAdmissionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new StudentAdmissionWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_AccptStdAdm;
    private javax.swing.JLabel Label_Assgmnt1;
    private javax.swing.JLabel Label_Assgmnt2;
    private javax.swing.JLabel Label_AttndnceReport;
    private javax.swing.JLabel Label_AttndnceReport1;
    private javax.swing.JLabel Label_AttndnceReport10;
    private javax.swing.JLabel Label_AttndnceReport11;
    private javax.swing.JLabel Label_AttndnceReport12;
    private javax.swing.JLabel Label_AttndnceReport13;
    private javax.swing.JLabel Label_AttndnceReport14;
    private javax.swing.JLabel Label_AttndnceReport15;
    private javax.swing.JLabel Label_AttndnceReport16;
    private javax.swing.JLabel Label_AttndnceReport17;
    private javax.swing.JLabel Label_AttndnceReport18;
    private javax.swing.JLabel Label_AttndnceReport2;
    private javax.swing.JLabel Label_AttndnceReport3;
    private javax.swing.JLabel Label_AttndnceReport4;
    private javax.swing.JLabel Label_AttndnceReport5;
    private javax.swing.JLabel Label_AttndnceReport6;
    private javax.swing.JLabel Label_AttndnceReport7;
    private javax.swing.JLabel Label_AttndnceReport8;
    private javax.swing.JLabel Label_AttndnceReport9;
    private javax.swing.JLabel Label_StdIDReport;
    private javax.swing.JLabel Label_StdNameReport;
    private javax.swing.JLabel Label_StdNameReport1;
    private javax.swing.JLabel Label_Test1;
    private javax.swing.JLabel Label_Test2;
    private javax.swing.JLabel Label_Test3;
    private javax.swing.JLabel Label_Test4;
    private javax.swing.JTextField TextField_Attndnce12;
    private javax.swing.JTextField TextField_Attndnce13;
    private javax.swing.JTextField TextField_Attndnce14;
    private javax.swing.JTextField TextField_Attndnce15;
    private javax.swing.JTextField TextField_Attndnce16;
    public javax.swing.JTextField TextField_RegDate;
    public javax.swing.JTextField TextField_Std10Adm;
    public javax.swing.JTextField TextField_Std12Adm;
    public javax.swing.JTextField TextField_StdAddAdm;
    public javax.swing.JTextField TextField_StdBloodAdm;
    public javax.swing.JTextField TextField_StdBranchAdm;
    public javax.swing.JTextField TextField_StdCategAdm;
    public javax.swing.JTextField TextField_StdDOBAdm;
    public javax.swing.JTextField TextField_StdEmailAdm;
    public javax.swing.JTextField TextField_StdFatherAdm;
    public javax.swing.JTextField TextField_StdGenAdm;
    public javax.swing.JTextField TextField_StdMotherAdm;
    public javax.swing.JTextField TextField_StdNameAdm;
    private javax.swing.JTextField TextField_StdNameReport1;
    public javax.swing.JTextField TextField_StdParentPhoneAdm;
    public javax.swing.JTextField TextField_StdPhoneAdm;
    public javax.swing.JTextField TextField_StdRegNumAdm;
    public javax.swing.JTextField TextField_StdScoreAdm;
    public javax.swing.JTextField TextField_StdSemAdm;
    public javax.swing.JTextField TextField_StdStreamAdm;
    public javax.swing.JTextField TextField_StdYearAdm;
    private javax.swing.JTextField TextField_Test3;
    private javax.swing.JTextField TextField_Test4;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
