/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.io.FileWriter;
import java.io.Reader;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class FacultyRegisterWindow extends javax.swing.JFrame {

    /**
     * Creates new form FacultyRegisterWindow
     */
    public FacultyRegisterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Test2 = new javax.swing.JLabel();
        Label_Test1 = new javax.swing.JLabel();
        Label_StdNameReport = new javax.swing.JLabel();
        TextField_RegNoFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport1 = new javax.swing.JLabel();
        Label_FcltyRepo_FcltyRegWin = new javax.swing.JLabel();
        TextField_GendFcltyReg = new javax.swing.JTextField();
        TextField_DegFcltyReg = new javax.swing.JTextField();
        Label_Assgmnt2 = new javax.swing.JLabel();
        TextField_DOBFcltyReg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TextField_ExprncFcltyReg = new javax.swing.JTextField();
        TextField_NameFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport = new javax.swing.JLabel();
        Label_StdIDReport = new javax.swing.JLabel();
        TextField_BloodFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport5 = new javax.swing.JLabel();
        Label_AttndnceReport2 = new javax.swing.JLabel();
        Label_AttndnceReport3 = new javax.swing.JLabel();
        TextField_DepartFcltyReg = new javax.swing.JTextField();
        TextField_YearFcltyReg = new javax.swing.JTextField();
        TextField_StreamFcltyReg = new javax.swing.JTextField();
        TextField_EmailFcltyRegFcltyReg = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TextField_MotherFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport10 = new javax.swing.JLabel();
        TextField_FatherFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport9 = new javax.swing.JLabel();
        TextField_ContFcltyReg = new javax.swing.JTextField();
        Button_AccptFcltyReg = new javax.swing.JButton();
        TextField_AddFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport11 = new javax.swing.JLabel();
        Label_AttndnceReport6 = new javax.swing.JLabel();
        TextField_ParentContFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport8 = new javax.swing.JLabel();
        Label_AttndnceReport7 = new javax.swing.JLabel();
        Button_DeclineFcltyReg = new javax.swing.JButton();
        jScrollBar2 = new javax.swing.JScrollBar();
        Label_Assgmnt3 = new javax.swing.JLabel();
        TextField_CategFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport4 = new javax.swing.JLabel();
        TextField_DesigtFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport12 = new javax.swing.JLabel();
        TextField_RegDateFcltyRegFcltyReg = new javax.swing.JTextField();
        Label_AttndnceReport13 = new javax.swing.JLabel();
        Button_AccptFcltyReg1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Faculty Registration");
        setAutoRequestFocus(false);

        Label_Test2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test2.setText("Gender:");

        Label_Test1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Test1.setText("Registration Number:");

        Label_StdNameReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_StdNameReport.setText("Name:");

        TextField_RegNoFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_RegNoFcltyReg.setEnabled(false);

        Label_AttndnceReport1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport1.setText("Experience:");

        Label_FcltyRepo_FcltyRegWin.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        Label_FcltyRepo_FcltyRegWin.setText("Faculty Details");

        TextField_GendFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_GendFcltyReg.setEnabled(false);

        TextField_DegFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_DegFcltyReg.setEnabled(false);

        Label_Assgmnt2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Assgmnt2.setText("Blood Group:");

        TextField_DOBFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_DOBFcltyReg.setEnabled(false);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        TextField_ExprncFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ExprncFcltyReg.setEnabled(false);

        TextField_NameFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_NameFcltyReg.setEnabled(false);

        Label_AttndnceReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport.setText("Degree:");

        Label_StdIDReport.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_StdIDReport.setText("D.O.B.:");

        TextField_BloodFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_BloodFcltyReg.setEnabled(false);

        Label_AttndnceReport5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport5.setText("Year:");

        Label_AttndnceReport2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport2.setText("Stream:");

        Label_AttndnceReport3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport3.setText("Department:");

        TextField_DepartFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_DepartFcltyReg.setEnabled(false);

        TextField_YearFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_YearFcltyReg.setEnabled(false);

        TextField_StreamFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StreamFcltyReg.setEnabled(false);

        TextField_EmailFcltyRegFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_EmailFcltyRegFcltyReg.setEnabled(false);
        TextField_EmailFcltyRegFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_EmailFcltyRegFcltyRegActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        TextField_MotherFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_MotherFcltyReg.setEnabled(false);

        Label_AttndnceReport10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport10.setText("Parent's Contact Number:");

        TextField_FatherFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_FatherFcltyReg.setEnabled(false);

        Label_AttndnceReport9.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport9.setText("Contact Number:");

        TextField_ContFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ContFcltyReg.setEnabled(false);
        TextField_ContFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ContFcltyRegActionPerformed(evt);
            }
        });

        Button_AccptFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_AccptFcltyReg.setText("Accept");
        Button_AccptFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AccptFcltyRegActionPerformed(evt);
            }
        });

        TextField_AddFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_AddFcltyReg.setEnabled(false);
        TextField_AddFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_AddFcltyRegActionPerformed(evt);
            }
        });

        Label_AttndnceReport11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport11.setText("E-mail Address:");

        Label_AttndnceReport6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport6.setText("Father's Name:");

        TextField_ParentContFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ParentContFcltyReg.setEnabled(false);
        TextField_ParentContFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ParentContFcltyRegActionPerformed(evt);
            }
        });

        Label_AttndnceReport8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport8.setText("Address:");

        Label_AttndnceReport7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport7.setText("Mother's Name:");

        Button_DeclineFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_DeclineFcltyReg.setText("Decline");

        jScrollBar2.setAutoscrolls(true);
        jScrollBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Label_Assgmnt3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Assgmnt3.setText("Category:");

        TextField_CategFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_CategFcltyReg.setEnabled(false);

        Label_AttndnceReport4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport4.setText("Designation:");

        TextField_DesigtFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_DesigtFcltyReg.setEnabled(false);

        Label_AttndnceReport12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport12.setText("Registration Date:");

        TextField_RegDateFcltyRegFcltyReg.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_RegDateFcltyRegFcltyReg.setEnabled(false);
        TextField_RegDateFcltyRegFcltyReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_RegDateFcltyRegFcltyRegActionPerformed(evt);
            }
        });

        Label_AttndnceReport13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_AttndnceReport13.setText("Download CV/Resume:");

        Button_AccptFcltyReg1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_AccptFcltyReg1.setText("Click to Download");
        Button_AccptFcltyReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AccptFcltyReg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Assgmnt2)
                            .addComponent(Label_AttndnceReport)
                            .addComponent(Label_AttndnceReport1)
                            .addComponent(Label_AttndnceReport3)
                            .addComponent(Label_AttndnceReport2)
                            .addComponent(Label_StdNameReport)
                            .addComponent(Label_StdIDReport)
                            .addComponent(Label_Test1)
                            .addComponent(Label_Test2)
                            .addComponent(Label_FcltyRepo_FcltyRegWin)
                            .addComponent(Label_Assgmnt3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_DegFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_BloodFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_StreamFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_DepartFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_ExprncFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168)
                                        .addComponent(Button_AccptFcltyReg))
                                    .addComponent(TextField_GendFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_RegNoFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_DOBFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_NameFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_CategFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_DesigtFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_EmailFcltyRegFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_ParentContFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextField_ContFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_AddFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_YearFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_FatherFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_MotherFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Button_AccptFcltyReg1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextField_RegDateFcltyRegFcltyReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addComponent(Button_DeclineFcltyReg))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_AttndnceReport4)
                                    .addComponent(Label_AttndnceReport6)
                                    .addComponent(Label_AttndnceReport7)
                                    .addComponent(Label_AttndnceReport5)
                                    .addComponent(Label_AttndnceReport8)
                                    .addComponent(Label_AttndnceReport9)
                                    .addComponent(Label_AttndnceReport10)
                                    .addComponent(Label_AttndnceReport11)
                                    .addComponent(Label_AttndnceReport12)
                                    .addComponent(Label_AttndnceReport13))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_FcltyRepo_FcltyRegWin)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_StdNameReport)
                    .addComponent(TextField_NameFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_StdIDReport)
                    .addComponent(TextField_DOBFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Test1)
                    .addComponent(TextField_RegNoFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Test2)
                    .addComponent(TextField_GendFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Assgmnt3)
                    .addComponent(TextField_CategFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Assgmnt2)
                    .addComponent(TextField_BloodFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport)
                    .addComponent(TextField_DegFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport1)
                    .addComponent(TextField_ExprncFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_AccptFcltyReg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport2)
                    .addComponent(TextField_StreamFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport3)
                    .addComponent(TextField_DepartFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport4)
                    .addComponent(TextField_DesigtFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport5)
                    .addComponent(TextField_YearFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport6)
                    .addComponent(TextField_FatherFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport7)
                    .addComponent(TextField_MotherFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport8)
                    .addComponent(TextField_AddFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport9)
                    .addComponent(TextField_ContFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport10)
                    .addComponent(TextField_ParentContFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport11)
                    .addComponent(TextField_EmailFcltyRegFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport12)
                    .addComponent(TextField_RegDateFcltyRegFcltyReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AttndnceReport13)
                    .addComponent(Button_AccptFcltyReg1))
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_DeclineFcltyReg)
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_EmailFcltyRegFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_EmailFcltyRegFcltyRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmailFcltyRegFcltyRegActionPerformed

    private void TextField_ContFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ContFcltyRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ContFcltyRegActionPerformed
String fid2;
int fid3;
    private void Button_AccptFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AccptFcltyRegActionPerformed
        // TODO add your handling code here:
        String stream = TextField_StreamFcltyReg.getText();
        String branch = TextField_DepartFcltyReg.getText();
        //String sem = TextField_StdSemAdm.getText();
        int GetID=0;
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@LocalHost:1521:XE","SYSTEM","sagar");
            String sql = "select count(*) from f_details where stream=? and branch=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, stream);
            ps.setString(2, branch);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                GetID=rs.getInt("s_id");
            }
        }
        catch(ClassNotFoundException e)
        {}
        catch(Exception e)
        {}
        java.util.Date today = Calendar.getInstance().getTime();
        SimpleDateFormat formatter = new SimpleDateFormat("yy");
        String s = formatter.format(today);
        int year = Integer.parseInt(s);
        fid3=GetID+1;
        fid2="fac"+stream+year+branch+fid3;
        FacultyRegAccept fr = new FacultyRegAccept();
        fr.setVisible(true);
        fr.TextField_NameFcltyAcpt.setText(TextField_NameFcltyReg.getText());
        fr.TextField_RegNoFcltyAcpt.setText(TextField_RegNoFcltyReg.getText());
        fr.TextField_GendFcltyAcpt.setText(TextField_GendFcltyReg.getText());
        fr.TextField_DegrFcltyAcpt.setText(TextField_DegFcltyReg.getText());
        fr.TextField_StreamFcltyAcpt.setText(TextField_StreamFcltyReg.getText());
        fr.TextField_DepartFcltyAcpt.setText(TextField_DepartFcltyReg.getText());
        fr.TextField_YearFcltyAcpt.setText(TextField_YearFcltyReg.getText());
        fr.TextField_IDFcltyAcpt.setText(fid2);
        this.setVisible(false);
    }//GEN-LAST:event_Button_AccptFcltyRegActionPerformed

    private void TextField_AddFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_AddFcltyRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_AddFcltyRegActionPerformed

    private void TextField_ParentContFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ParentContFcltyRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ParentContFcltyRegActionPerformed

    private void TextField_RegDateFcltyRegFcltyRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_RegDateFcltyRegFcltyRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RegDateFcltyRegFcltyRegActionPerformed

    private void Button_AccptFcltyReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AccptFcltyReg1ActionPerformed
        // TODO add your handling code here:
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","sagar");
                String sql = "select * from f_regostration where regist_no=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, TextField_RegNoFcltyReg.getText());
                ResultSet rs = ps.executeQuery();
                rs.next();
                Clob c = rs.getClob("cv");
                Reader r = c.getCharacterStream();
                java.util.Date today = Calendar.getInstance().getTime();
                SimpleDateFormat formatter = new SimpleDateFormat("dd-mm-yyyy-hh.mm.ss");
                String s =TextField_NameFcltyReg+" "+TextField_RegNoFcltyReg+"downloaded at"+formatter.format(today);
                FileWriter fw = new FileWriter("A:\\CV-RESUME\\"+s+".txt");
                int i;
                int retr = JOptionPane.showConfirmDialog(this, "Are you sure you want to Download the CV?");
                if(retr==0)
                {
                    while((i=r.read())!=-1)
                    {
                        fw.write((char)i);
                        System.out.println(i);
                    }
                    JOptionPane.showMessageDialog(this,"Download Successful");
                }
                else if(retr==1 || retr==2)
                {
                    JOptionPane.showMessageDialog(this, "CV not Downloated");
                }
                fw.close();
                con.close();
            }
            catch(ClassNotFoundException e)
            {}  
            catch(Exception e)
            {}
    }//GEN-LAST:event_Button_AccptFcltyReg1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FacultyRegisterWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_AccptFcltyReg;
    public javax.swing.JButton Button_AccptFcltyReg1;
    public javax.swing.JButton Button_DeclineFcltyReg;
    private javax.swing.JLabel Label_Assgmnt2;
    private javax.swing.JLabel Label_Assgmnt3;
    private javax.swing.JLabel Label_AttndnceReport;
    private javax.swing.JLabel Label_AttndnceReport1;
    private javax.swing.JLabel Label_AttndnceReport10;
    private javax.swing.JLabel Label_AttndnceReport11;
    private javax.swing.JLabel Label_AttndnceReport12;
    private javax.swing.JLabel Label_AttndnceReport13;
    private javax.swing.JLabel Label_AttndnceReport2;
    private javax.swing.JLabel Label_AttndnceReport3;
    private javax.swing.JLabel Label_AttndnceReport4;
    private javax.swing.JLabel Label_AttndnceReport5;
    private javax.swing.JLabel Label_AttndnceReport6;
    private javax.swing.JLabel Label_AttndnceReport7;
    private javax.swing.JLabel Label_AttndnceReport8;
    private javax.swing.JLabel Label_AttndnceReport9;
    private javax.swing.JLabel Label_FcltyRepo_FcltyRegWin;
    private javax.swing.JLabel Label_StdIDReport;
    private javax.swing.JLabel Label_StdNameReport;
    private javax.swing.JLabel Label_Test1;
    private javax.swing.JLabel Label_Test2;
    public javax.swing.JTextField TextField_AddFcltyReg;
    public javax.swing.JTextField TextField_BloodFcltyReg;
    public javax.swing.JTextField TextField_CategFcltyReg;
    public javax.swing.JTextField TextField_ContFcltyReg;
    public javax.swing.JTextField TextField_DOBFcltyReg;
    public javax.swing.JTextField TextField_DegFcltyReg;
    public javax.swing.JTextField TextField_DepartFcltyReg;
    public javax.swing.JTextField TextField_DesigtFcltyReg;
    public javax.swing.JTextField TextField_EmailFcltyRegFcltyReg;
    public javax.swing.JTextField TextField_ExprncFcltyReg;
    public javax.swing.JTextField TextField_FatherFcltyReg;
    public javax.swing.JTextField TextField_GendFcltyReg;
    public javax.swing.JTextField TextField_MotherFcltyReg;
    public javax.swing.JTextField TextField_NameFcltyReg;
    public javax.swing.JTextField TextField_ParentContFcltyReg;
    public javax.swing.JTextField TextField_RegDateFcltyRegFcltyReg;
    public javax.swing.JTextField TextField_RegNoFcltyReg;
    public javax.swing.JTextField TextField_StreamFcltyReg;
    public javax.swing.JTextField TextField_YearFcltyReg;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
