/**
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class LoginPage12 extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage1
     */String a,c,d;
    
    public LoginPage12() {
        initComponents();
        Label_HashPassWarng_Login.setVisible(false);
        Label_HashUserIDWarng_Login.setVisible(false);
        Label_Warning_Login.setVisible(false);
        //Label_Warning_Login2.setVisible(false);
        //Label_Warning_Login1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Panel_Login = new javax.swing.JPanel();
        Label_Login = new javax.swing.JLabel();
        Label_UserID_Loign = new javax.swing.JLabel();
        Label_Password_Login = new javax.swing.JLabel();
        UserID = new javax.swing.JTextField();
        Label_Categ_Login = new javax.swing.JLabel();
        Categ_Login = new javax.swing.JComboBox();
        Button_Reset_Login = new javax.swing.JButton();
        Button_Login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        Label_Warning_Login = new javax.swing.JLabel();
        Label_HashUserIDWarng_Login = new javax.swing.JLabel();
        Label_HashPassWarng_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Panel_Login.setBackground(new java.awt.Color(204, 204, 204));
        Panel_Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Label_Login.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        Label_Login.setText("Login Form");

        Label_UserID_Loign.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        Label_UserID_Loign.setText("UserID:");

        Label_Password_Login.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        Label_Password_Login.setText("Password:");

        UserID.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        UserID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDActionPerformed(evt);
            }
        });

        Label_Categ_Login.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        Label_Categ_Login.setText("Category:");

        Categ_Login.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Categ_Login.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----- Select Category -----", "Admin", "clerk", "Faculty", "student" }));
        Categ_Login.setBorder(null);

        Button_Reset_Login.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_Reset_Login.setText(" Reset");
        Button_Reset_Login.setBorder(new javax.swing.border.SoftBevelBorder(0));
        Button_Reset_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Reset_LoginActionPerformed(evt);
            }
        });

        Button_Login.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Button_Login.setText("Login");
        Button_Login.setBorder(new javax.swing.border.SoftBevelBorder(0));
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        Password.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Label_Warning_Login.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Label_Warning_Login.setForeground(new java.awt.Color(255, 0, 0));
        Label_Warning_Login.setText("!!Please enter valid UserID!!");

        Label_HashUserIDWarng_Login.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        Label_HashUserIDWarng_Login.setForeground(new java.awt.Color(255, 0, 0));
        Label_HashUserIDWarng_Login.setText("*");

        Label_HashPassWarng_Login.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        Label_HashPassWarng_Login.setForeground(new java.awt.Color(255, 0, 0));
        Label_HashPassWarng_Login.setText("*");

        javax.swing.GroupLayout Panel_LoginLayout = new javax.swing.GroupLayout(Panel_Login);
        Panel_Login.setLayout(Panel_LoginLayout);
        Panel_LoginLayout.setHorizontalGroup(
            Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Reset_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(Panel_LoginLayout.createSequentialGroup()
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Warning_Login)
                            .addComponent(Label_Login))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_LoginLayout.createSequentialGroup()
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Password_Login)
                            .addComponent(Label_Categ_Login)
                            .addComponent(Label_UserID_Loign))
                        .addGap(70, 70, 70)
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserID)
                            .addComponent(Password)
                            .addComponent(Categ_Login, 0, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_HashUserIDWarng_Login)
                            .addComponent(Label_HashPassWarng_Login))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LoginLayout.createSequentialGroup()
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        Panel_LoginLayout.setVerticalGroup(
            Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LoginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Label_Warning_Login)
                .addGap(18, 18, 18)
                .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_UserID_Loign)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_HashUserIDWarng_Login))
                .addGap(28, 28, 28)
                .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Password_Login)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_HashPassWarng_Login))
                .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_LoginLayout.createSequentialGroup()
                        .addGap(38, 108, Short.MAX_VALUE)
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Reset_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_LoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(Panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Categ_Login)
                            .addComponent(Categ_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        Label_Warning_Login.setVisible(false);
        Label_HashUserIDWarng_Login.setVisible(false);
        Label_HashPassWarng_Login.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(Panel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Panel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Reset_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Reset_LoginActionPerformed
        // TODO add your handling code here:
        UserID.setText(null);
        Password.setText(null);
        Categ_Login.setSelectedIndex(0);
        Label_HashPassWarng_Login.setVisible(false);
        Label_HashUserIDWarng_Login.setVisible(false);
        Label_Warning_Login.setVisible(false);
        //Label_Warning_Login2.setVisible(false);
        //Label_Warning_Login1.setVisible(false);
        
    }//GEN-LAST:event_Button_Reset_LoginActionPerformed
String us,pa,cat,WelcomeName;
    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
       // TODO add your handling code here:
                        a=UserID.getText();
                        char b[]=Password.getPassword();
                        String p= new String(b);
                        c=Categ_Login.getSelectedItem().toString();
                        
       try
		{
		        Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","qwer1234");
                        String sql="select * from LOGIN" ;
			PreparedStatement ps=con.prepareStatement(sql);
                        //ps.setString(1,a);
                       // ps.setString(2,p);
                        //ps.setString(3,c);
			ResultSet rs=ps.executeQuery();	
			while(rs.next())
                        {
                                us = rs.getString("USER_ID");
                                pa = rs.getString("USER_PASS");
                                cat = rs.getString("USER_CAT");
                                String WelcomeName = rs.getString("user_name");
                            //JOptionPane.showMessageDialog(null, us);
                            //JOptionPane.showMessageDialog(null, pa);
                               //S JOptionPane.showMessageDialog(null, c);
			    if(a.equals(us) )
                            { 
                                if(p.equals(pa) )
                                {   
                                    if(c.equals(cat))
                                    {     
                                        if(c.equals("clerk"))
                                        {
                                         this.setVisible(false);
                                        Clerk2_1 u = new Clerk2_1();
                                         u.clerk(a,WelcomeName);
                                          u.setVisible(true); 
                                        }
                                        else if (c.equals("student"))
                                        {
                                            this.setVisible(false);
                                            Home1Page1 n=new Home1Page1();
                                            n.student(a,WelcomeName);
                                             n.setVisible(true);
                                        }
                                        else if(c.equals("Faculty")){
                                            this.setVisible(false);
                                            CoursePage cp = new CoursePage();
                                            cp.abc(a,WelcomeName);
                                            JOptionPane.showMessageDialog(null, "after label");
                                            cp.setVisible(true);
                                        }
                                        else if(c.equals("Admin")){
                                            this.setVisible(false);
                                            Home1Page u = new Home1Page();
                                            u.Label_WelcomeUserName.setText(WelcomeName);
                                            u.setVisible(true);
                                        }
                                     }
                                    else
                                    {   
                                        Label_HashPassWarng_Login.setVisible(true);
                                        Label_HashUserIDWarng_Login.setVisible(false);
                                        Label_Warning_Login.setVisible(false);
                                        //Label_Warning_Login2.setVisible(true);
                                        //Label_Warning_Login1.setVisible(false);
                                        JOptionPane.showMessageDialog(null,"invalid category");
                                        
                                    }           
                                }
                                else
                                {
                                     Label_HashUserIDWarng_Login.setVisible(true);
                                     //Label_Warning_Login1.setVisible(true);
                                     //Label_Warning_Login2.setVisible(false);
                                     Label_Warning_Login.setVisible(false);
                                    JOptionPane.showMessageDialog(null,"invalid password");
                                
                                }
                                
                            }
                            else
                            {
                                Label_Warning_Login.setVisible(true);
                                //Label_Warning_Login1.setVisible(false);
                                //Label_Warning_Login2.setVisible(false);
                            }
                            /*else if(a!=us || a.equals(" "))
                            {
                                Label_Warning_Login.setVisible(true);
                            }
                            else if(p!=pa||p.equals(" "))
                            {
                                JOptionPane.showMessageDialog(null,"INVALID PASSWORD");
                            }  
                            else if(c.equals(" ")||c!=cat)
                            {
                                 JOptionPane.showMessageDialog(null,"INVALID CATEGORY");
                            }*/
                        
		}
                }
		catch(ClassNotFoundException e)
		{
                    JOptionPane.showMessageDialog(null,e);
		}
		catch(Exception e) 
		{
                    JOptionPane.showMessageDialog(null,e);
		}
        //this.setVisible(true);    
      
       
      
    }//GEN-LAST:event_Button_LoginActionPerformed
    public void abc()
    {
        
         
        
    }
    public void abc1()
    {
       
    }
    private void UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_UserIDActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginPage12().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_Reset_Login;
    private javax.swing.JComboBox Categ_Login;
    private javax.swing.JLabel Label_Categ_Login;
    private javax.swing.JLabel Label_HashPassWarng_Login;
    private javax.swing.JLabel Label_HashUserIDWarng_Login;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Password_Login;
    private javax.swing.JLabel Label_UserID_Loign;
    private javax.swing.JLabel Label_Warning_Login;
    public javax.swing.JPanel Panel_Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserID;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}