/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static lms.Exam_details.e_time;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Que extends javax.swing.JFrame {

    /**
     * Creates new form Que_try
     */
    String aa,question1,aa1,bb1,cc1,dd1,answer1,

    /**
     * Creates new form Que
     */
    bb,

    /**
     * Creates new form Que
     */
    cc,

    /**
     * Creates new form Que
     */
    dd,

    /**
     * Creates new form Que
     */
    question,

    /**
     * Creates new form Que
     */
    corr,

    /**
     * Creates new form Que
     */
    tot2,

    /**
     * Creates new form Que
     */
    k1,

    /**
     * Creates new form Que
     */
    eno;
    static int tot1,k=1;
    //int i;
    int number=0;
    String exam_id="";
     public Que(int b,String c)
     {
         number=b;
         exam_id=c;
         initComponents();
     }
    public Que() {
        initComponents();
        Exam_details y=new Exam_details();
        eno=y.id;
    }
 public void question_edit()
    {
        try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","qwer1234");
                String sql="select * from question where question_no=? and exam_id=?";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setInt(1,number);
                ps.setString(2,exam_id);
                ResultSet rs= ps.executeQuery();
                while(rs.next())
                {
                    question_box.setText(rs.getString("Question"));
                    answer_a.setText(rs.getString("A"));
                    answer_b.setText(rs.getString("B"));
                    answer_c.setText(rs.getString("C"));
                    answer_d.setText(rs.getString("D"));
                }
        }
        catch(Exception e)
        {
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question_box = new javax.swing.JTextArea();
        answer_a = new javax.swing.JTextField();
        answer_c = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reset_question = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        question_no = new javax.swing.JLabel();
        answer_b = new javax.swing.JTextField();
        answer_d = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        preview_question = new javax.swing.JLabel();
        answer_correct = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        a_answer = new javax.swing.JLabel();
        b_answer = new javax.swing.JLabel();
        c_answer = new javax.swing.JLabel();
        d_answer = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        save_question = new javax.swing.JButton();
        save_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        question_box.setColumns(20);
        question_box.setRows(5);
        jScrollPane1.setViewportView(question_box);

        answer_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_cActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel1.setText("A:");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel2.setText("B:");

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel3.setText("C:");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel4.setText("D:");

        reset_question.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        reset_question.setText("RESET");
        reset_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_questionActionPerformed(evt);
            }
        });

        preview.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        preview.setText("PREVIEW");
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel5.setText("QUESTION:");

        question_no.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        question_no.setText("no");

        answer_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(reset_question, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(320, 320, 320)
                                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(answer_d, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                .addComponent(answer_c, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(answer_b, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(answer_a, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(question_no))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(question_no))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_question, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PREVIEW"));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preview_question)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preview_question)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        answer_correct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        answer_correct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_correctActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        jLabel7.setText("CORRECT ANS:");

        a_answer.setBackground(new java.awt.Color(255, 255, 255));
        a_answer.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        a_answer.setText(".");

        b_answer.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        b_answer.setText(".");

        c_answer.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        c_answer.setText(".");

        d_answer.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        d_answer.setText(".");

        jLabel6.setText("A:");

        jLabel11.setText("C:");

        jLabel12.setText("B:");

        jLabel13.setText("D:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(c)
                                        .addGap(12, 12, 12)
                                        .addComponent(a))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(d_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(39, 39, 39)
                                            .addComponent(b_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(answer_correct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(a_answer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(b_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(c))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(c_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(d_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_correct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        save_question.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        save_question.setText("SAVE QUESTION");
        save_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_questionActionPerformed(evt);
            }
        });

        save_exit.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        save_exit.setText("SAVE & EXIT");
        save_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_exit)
                .addGap(29, 29, 29)
                .addComponent(save_question)
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_exit)
                    .addComponent(save_question))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void Question_num()
            {
                    question_no.setText("1");
            }
    private void answer_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_cActionPerformed
    
    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        // TODO add your handling code here:
        question=question_box.getText();
        aa=answer_a.getText();
        bb=answer_b.getText();
        cc=answer_c.getText();
        dd=answer_d.getText();
        preview_question.setText(question);
        a_answer.setText(aa);
        b_answer.setText(bb);
        c_answer.setText(cc);
        d_answer.setText(dd);
        answer_correct.setEnabled(true);
        save_question.setEnabled(true);
        save_exit.setEnabled(true);
        Exam_details e=new Exam_details();
        tot1=Integer.parseInt(e.tot); 
        if(tot1==1)
        {
            save_exit.setVisible(true);
            save_question.setVisible(false);
        }
        else
        {
        save_question.setEnabled(true);
        }
    }//GEN-LAST:event_previewActionPerformed
    public void save_exit()
    {
        save_exit.setEnabled(false);
    }
    public void save_question()
    {
        save_question.setEnabled(false);
    }
    private void save_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_questionActionPerformed

        // TODO add your handling code here:
        Exam_details e=new Exam_details();
        tot1=Integer.parseInt(e.tot); 
        //System.out.println(tot1);
    
        preview_question.setText(question);
        a_answer.setText(aa);
        b_answer.setText(bb);
        c_answer.setText(cc);
        d_answer.setText(dd);
        corr=answer_correct.getSelectedItem().toString();
        
        try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","qwer1234");
                String sql="insert into question values(?,?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,eno);
                ps.setInt(2,k);
                ps.setString(3, question);
                ps.setString(4, aa);
                ps.setString(5, bb);
                ps.setString(6,cc);
                ps.setString(7,dd);
                ps.setString(8, corr);
                int i=ps.executeUpdate();
                if(i>0)
                {
                    question_box.setText("");
                     a_answer.setText("");
                     b_answer.setText("");
                     c_answer.setText("");
                     d_answer.setText("");
                     preview_question.setText("");
                     answer_a.setText("");
                     answer_b.setText("");
                     answer_c.setText("");
                     answer_d.setText("");
                     answer_correct.setSelectedItem("A");
                     k++;   
                     k1=Integer.toString(k);
                     question_no.setText(k1);
                     
                } 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,e1);
        
        }
        answer_correct.setEnabled(false);
        save_exit.setEnabled(false);
        save_question.setEnabled(false);
        if(k==tot1)
        {
                save_exit.setVisible(true);
                save_question.setVisible(false);
        }
        

    }//GEN-LAST:event_save_questionActionPerformed

    
    public void nosave()
    {
        save_question.setVisible(false);
    }
    public void saveDisable()
    {
        save_question.setEnabled(false);
    }
    private void answer_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_bActionPerformed

    private void reset_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_questionActionPerformed
        // TODO add your handling code here:
        question_box.setText("");
        answer_a.setText("");
        answer_b.setText("");
        answer_c.setText("");
        answer_d.setText("");
    }//GEN-LAST:event_reset_questionActionPerformed

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_previewMouseClicked
    void saveexit()
    {
        save_exit.setVisible(false);
    }
    private void save_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_exitActionPerformed
        // TODO add your handling code here:
        preview_question.setText(question);
        a_answer.setText(aa);
        b_answer.setText(bb);
        c_answer.setText(cc);
        d_answer.setText(dd);
        corr=answer_correct.getSelectedItem().toString();
        
        
        if(tot1==1)
        {
        try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","qwer1234");
                String sql="insert into question values(?,?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,eno);
                ps.setInt(2,k);
                ps.setString(3, question);
                ps.setString(4, aa);
                ps.setString(5, bb);
                ps.setString(6,cc);
                ps.setString(7,dd);
                ps.setString(8, corr);
                int j=ps.executeUpdate();
                if(j>0)
                {
                    question_box.setText("");
                     a_answer.setText("");
                     b_answer.setText("");
                     c_answer.setText("");
                     d_answer.setText("");
                     preview_question.setText("");
                     answer_a.setText("");
                     answer_b.setText("");
                     answer_c.setText("");
                     answer_d.setText("");
                     k++;
                        Test_details_logout t= new Test_details_logout();
                        t.setVisible(true);
                        this.setVisible(false);
                } 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,e1);
        }
             
       }
        
        else if(tot1>1)
        {
        try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","qwer1234");
                String sql="insert into question values(?,?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,eno);
                ps.setInt(2,k);
                ps.setString(3, question);
                ps.setString(4, aa);
                ps.setString(5, bb);
                ps.setString(6,cc);
                ps.setString(7,dd);
                ps.setString(8, corr);int j=ps.executeUpdate();
                if(j>0)
                {
                    question_box.setText("");
                     a_answer.setText("");
                     b_answer.setText("");
                     c_answer.setText("");
                     d_answer.setText("");
                     preview_question.setText("");
                     answer_a.setText("");
                     answer_b.setText("");
                     answer_c.setText("");
                     answer_d.setText("");
                     k++;
                     Test_details_logout t= new Test_details_logout();
                     t.setVisible(true);
                     this.setVisible(false);
                } 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,e1);
        }
              
       }
        
    }//GEN-LAST:event_save_exitActionPerformed

    public void answer_disable()
    {
        answer_correct.setEnabled(false);
    }
    private void answer_correctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_correctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_correctActionPerformed

    
    public void preview_hide2()
    {
        preview.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Que().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a_answer;
    private javax.swing.JTextField answer_a;
    private javax.swing.JTextField answer_b;
    private javax.swing.JTextField answer_c;
    private javax.swing.JComboBox answer_correct;
    private javax.swing.JTextField answer_d;
    private javax.swing.JLabel b;
    private javax.swing.JLabel b_answer;
    private javax.swing.JLabel c;
    private javax.swing.JLabel c_answer;
    private javax.swing.JLabel d_answer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton preview;
    private javax.swing.JLabel preview_question;
    private javax.swing.JTextArea question_box;
    private javax.swing.JLabel question_no;
    private javax.swing.JButton reset_question;
    private javax.swing.JButton save_exit;
    private javax.swing.JButton save_question;
    // End of variables declaration//GEN-END:variables
}
