/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

/**
 *
 * @author Sony
 */
public class StudentListWindow extends javax.swing.JFrame {

    /**
     * Creates new form StudentListWindow
     */
    public StudentListWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextField_ScoreStdLst = new javax.swing.JTextField();
        TextField_AddStdLst = new javax.swing.JTextField();
        TextField_ContactStdLst = new javax.swing.JTextField();
        TextField_ParentConStdLst = new javax.swing.JTextField();
        TextField_EmailStdLst = new javax.swing.JTextField();
        TextField_MotherStdLst = new javax.swing.JTextField();
        TextField_FatherStdLst = new javax.swing.JTextField();
        TextField_AdmYrStdLst = new javax.swing.JTextField();
        TextField_10StdLst = new javax.swing.JTextField();
        TextField_12StdLst = new javax.swing.JTextField();
        TextField_BloodStdLst = new javax.swing.JTextField();
        TextField_StreamStdLst = new javax.swing.JTextField();
        TextField_BranchStdLst = new javax.swing.JTextField();
        TextField_GendStdLst = new javax.swing.JTextField();
        TextField_CategStdLst = new javax.swing.JTextField();
        TextField_DOBStdLst = new javax.swing.JTextField();
        TextField_NameStdLst = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Button_DoneStdLst = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        TextField_IDStdLst = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel20 = new javax.swing.JLabel();
        TextField_RegNoStdLst = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 20)); // NOI18N
        jLabel1.setText("Student Details");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setText("D.O.B.:");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel5.setText("Category:");

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group:");

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setText("Stream:");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setText("Branch:");

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel9.setText("10th:");

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel10.setText("12th:");

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel11.setText("Entrance Test Score:");

        jLabel12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel12.setText("Year of Admission:");

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel13.setText("Father's Name:");

        jLabel14.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel14.setText("Mother's Name:");

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel15.setText("Address:");

        jLabel16.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel16.setText("Contact Number:");

        jLabel17.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel17.setText("Parent's Contact Number:");

        jLabel18.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel18.setText("E-mail Address:");

        TextField_ScoreStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ScoreStdLst.setEnabled(false);

        TextField_AddStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_AddStdLst.setEnabled(false);

        TextField_ContactStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ContactStdLst.setEnabled(false);

        TextField_ParentConStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_ParentConStdLst.setEnabled(false);
        TextField_ParentConStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ParentConStdLstActionPerformed(evt);
            }
        });

        TextField_EmailStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_EmailStdLst.setEnabled(false);
        TextField_EmailStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_EmailStdLstActionPerformed(evt);
            }
        });

        TextField_MotherStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_MotherStdLst.setEnabled(false);
        TextField_MotherStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MotherStdLstActionPerformed(evt);
            }
        });

        TextField_FatherStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_FatherStdLst.setEnabled(false);
        TextField_FatherStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_FatherStdLstActionPerformed(evt);
            }
        });

        TextField_AdmYrStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_AdmYrStdLst.setEnabled(false);
        TextField_AdmYrStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_AdmYrStdLstActionPerformed(evt);
            }
        });

        TextField_10StdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_10StdLst.setEnabled(false);
        TextField_10StdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_10StdLstActionPerformed(evt);
            }
        });

        TextField_12StdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_12StdLst.setEnabled(false);
        TextField_12StdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_12StdLstActionPerformed(evt);
            }
        });

        TextField_BloodStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_BloodStdLst.setEnabled(false);
        TextField_BloodStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_BloodStdLstActionPerformed(evt);
            }
        });

        TextField_StreamStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_StreamStdLst.setEnabled(false);
        TextField_StreamStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StreamStdLstActionPerformed(evt);
            }
        });

        TextField_BranchStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_BranchStdLst.setEnabled(false);
        TextField_BranchStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_BranchStdLstActionPerformed(evt);
            }
        });

        TextField_GendStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_GendStdLst.setEnabled(false);
        TextField_GendStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_GendStdLstActionPerformed(evt);
            }
        });

        TextField_CategStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_CategStdLst.setEnabled(false);
        TextField_CategStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_CategStdLstActionPerformed(evt);
            }
        });

        TextField_DOBStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_DOBStdLst.setEnabled(false);
        TextField_DOBStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DOBStdLstActionPerformed(evt);
            }
        });

        TextField_NameStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_NameStdLst.setEnabled(false);
        TextField_NameStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NameStdLstActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        Button_DoneStdLst.setText("Done");
        Button_DoneStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DoneStdLstActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel19.setText("Student ID:");

        TextField_IDStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_IDStdLst.setEnabled(false);
        TextField_IDStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_IDStdLstActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setText("Registration Number:");

        TextField_RegNoStdLst.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        TextField_RegNoStdLst.setEnabled(false);
        TextField_RegNoStdLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_RegNoStdLstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel19))
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_IDStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_DOBStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_NameStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel20))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_StreamStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addComponent(Button_DoneStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextField_RegNoStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_BranchStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_GendStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_CategStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_BloodStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_10StdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_FatherStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_EmailStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_MotherStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_ContactStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_ParentConStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_AddStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_12StdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_AdmYrStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField_ScoreStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(52, 52, 52))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextField_NameStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TextField_IDStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextField_DOBStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextField_GendStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextField_CategStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TextField_BloodStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextField_StreamStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TextField_BranchStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TextField_10StdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TextField_12StdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TextField_ScoreStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TextField_AdmYrStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TextField_FatherStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TextField_MotherStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TextField_AddStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TextField_ContactStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TextField_ParentConStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(TextField_EmailStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(Button_DoneStdLst)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TextField_RegNoStdLst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_ParentConStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ParentConStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ParentConStdLstActionPerformed

    private void TextField_EmailStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_EmailStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmailStdLstActionPerformed

    private void TextField_MotherStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MotherStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_MotherStdLstActionPerformed

    private void TextField_FatherStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_FatherStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_FatherStdLstActionPerformed

    private void TextField_AdmYrStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_AdmYrStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_AdmYrStdLstActionPerformed

    private void TextField_10StdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_10StdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_10StdLstActionPerformed

    private void TextField_12StdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_12StdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_12StdLstActionPerformed

    private void TextField_BloodStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BloodStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_BloodStdLstActionPerformed

    private void TextField_StreamStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StreamStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StreamStdLstActionPerformed

    private void TextField_BranchStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BranchStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_BranchStdLstActionPerformed

    private void TextField_GendStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_GendStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_GendStdLstActionPerformed

    private void TextField_CategStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CategStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CategStdLstActionPerformed

    private void TextField_DOBStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DOBStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DOBStdLstActionPerformed

    private void TextField_NameStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NameStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NameStdLstActionPerformed

    private void Button_DoneStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DoneStdLstActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_DoneStdLstActionPerformed

    private void TextField_IDStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_IDStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_IDStdLstActionPerformed

    private void TextField_RegNoStdLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_RegNoStdLstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_RegNoStdLstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StudentListWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button_DoneStdLst;
    public javax.swing.JTextField TextField_10StdLst;
    public javax.swing.JTextField TextField_12StdLst;
    public javax.swing.JTextField TextField_AddStdLst;
    public javax.swing.JTextField TextField_AdmYrStdLst;
    public javax.swing.JTextField TextField_BloodStdLst;
    public javax.swing.JTextField TextField_BranchStdLst;
    public javax.swing.JTextField TextField_CategStdLst;
    public javax.swing.JTextField TextField_ContactStdLst;
    public javax.swing.JTextField TextField_DOBStdLst;
    public javax.swing.JTextField TextField_EmailStdLst;
    public javax.swing.JTextField TextField_FatherStdLst;
    public javax.swing.JTextField TextField_GendStdLst;
    public javax.swing.JTextField TextField_IDStdLst;
    public javax.swing.JTextField TextField_MotherStdLst;
    public javax.swing.JTextField TextField_NameStdLst;
    public javax.swing.JTextField TextField_ParentConStdLst;
    public javax.swing.JTextField TextField_RegNoStdLst;
    public javax.swing.JTextField TextField_ScoreStdLst;
    public javax.swing.JTextField TextField_StreamStdLst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
